config/routes.rb
MaileeSiteRails3::Application.routes.draw do

  get "cases(.html)", :controller => :site, :action => :cases, :as => :cases
  post "mailee", :controller => :site, :action => :mailee, :as => :mailee
  get "politica_anti_spam(.html)", :controller => :site, :action => :spam, :as => :spam
  get "cadastro(.html)", :controller => :site, :action => :signup, :as => :signup
  get "termos_de_uso(.html)", :controller => :site, :action => :terms, :as => :terms
  get "politica_de_privacidade(.html)", :controller => :site, :action => :privacy, :as => :privacy
  get "melhores_praticas(.html)", :controller => :site, :action => :best_practices, :as => :best_practices
  get "recursos(.html)", :controller => :site, :action => :tour, :as => :tour
  get "precos(.html)", :controller => :site, :action => :prices, :as => :prices
  get "bad_browsers(.html)", :controller => :site, :action => :bad_browsers, :as => :bad_browsers

  get "agencias(.html)", :controller => :site, :action => :agencies, :as => :agencies

  root :to => 'site#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
# encoding: utf-8
class SiteController < ApplicationController

  # caches_page :index, :tour, :bad_browsers, :privacy, :terms, :prices

  def index
  end

  def agencies
    # title "Agências"
    #render :nothing => true, :status => :not_found if Rails.env.production?
    @referrer = params["referrer"]
    render :layout => false
  end

  def bad_browsers
    title "Navegador inválido"
  end

  def best_practices
    title "Melhores práticas"
  end

  def form_ok; end
  def form_error; end

  def prices
    title "Preços"
  end

  def privacy
    title "Política de Privacidade"
  end

  def signup
    @referrer = params["referrer"]
  end

  def spam
    title "Política Anti-SPAM"
  end

  def terms
    title "Termos de Uso"
  end

  def tour
    title "Principais recursos"
  end

  def cases
    title "Cases"
  end

  def mailee
    require 'net/http'
    ok = 'http://www.google.com'
    error = 'http://www.yahoo.com'
    url = 'http://mailee.mailee.me/go/add_contact_form'
    data = {:name => params[:name], :email => params[:email], :key => "f9b5d3", "list[]" => 22642, :url_ok => ok, :url_error => error}
    res = Net::HTTP.post_form(URI.parse(url), data)
    render :json => {:ok => res['location'] == ok}
  end

  # Sends the email via ajax.
  def contact
    Site.contact(params).deliver
    render :json => {:ok => true}.to_json
  rescue
    render :json => {:ok => false}.to_json
  end

protected

  before_filter :set_defaults

  def set_defaults
    title "Email marketing com criador de templates, geolocalização e integração com redes sociais"
    @online = File.read('online.txt') == 'true' rescue false
  end

  def title(title)
    @title = "%s · Email Marketing 2.0 · Mailee.me" % title
  end

  helper_method :selected_menu, :body_id

  def selected_menu
    @selected_menu ||= action_name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper

  def kase img, name, bio, about, desc
    render :partial => 'kase', :locals => {:img => img, :name => name, :bio => bio, :about => about, :desc => desc}
  end
  
  def env_path
    case Rails.env
      when 'development'
         'wizee.net'
      when 'preproduction'
        'maileebeta.me'
      when 'production'
        'mailee.me'
    end
  end
  def selected(current);    selected_menu.to_s == current.to_s ? 'current_view' : '';             end
  def signup_iframe_path;   "https://signups.#{env_path}/signup/new?referrer=#{params[:referrer]}"; end

  def global_login;         'https://signups.mailee.me/site_sessions/new' end
  def blog_path;            'http://blog.mailee.me' end
  def twitter_path;         'http://twitter.com/maileeme' end
  def support_mail;         'mailto:suporte@mailee.me' end
  def commercial_mail;      'mailto:comercial@mailee.me' end
  def help_path(page=nil);  "http://help.mailee.me/#{page}" end
end

app/helpers/working_on_helper.rb
module WorkingOnHelper
end

app/views/layouts/_footer.haml
.footer_wrapper
  .span-5.append-1
    %h3 #{t('footer.policy')}
    %ul
      %li= link_to t('footer.anti_spam_policy'), spam_path
      %li= link_to t('footer.privacy_policy'), privacy_path
      %li= link_to t('footer.terms_of_use'), terms_path
  .span-5.append-1
    %h3 Documentação
    %ul
      %li= link_to 'Help', help_path
      %li= link_to 'Melhores práticas', best_practices_path
  .span-5.append-1
    %h3 entre em contato
    %ul.contact_list
      %li= link_to 'Suporte', support_mail
      %li= link_to 'Comercial', commercial_mail
    %hr
    .web_links
      = link_to((image_tag('social/rss_16.png') + ' Blog'), blog_path, :style => 'margin: 2px 0')
      %br
      = link_to((image_tag('social/facebook_16.png') + ' Facebook'), 'http://facebook.com/mailee.me',:style => 'margin: 2px 0')
      %br
      = link_to((image_tag('social/twitter_16.png') + ' Twitter'), twitter_path, :style => 'margin: 2px 0')
  .span-6.last
    #newsletter{:style => 'height:200px;' }
      %h3 Receba nossa newsletter
      #mailee_ok.hide
        %h4 Email cadastrado com sucesso.
        %p Você receberá uma confirmação por email.
        = link_to 'Cadastrar novo email.', '#', :class => 'subscribe_another_email'
      #mailee_error.hide
        %h4 Ocorreu um erro ao cadastrar o email
        = link_to 'Tentar novamente', '#', :class => 'subscribe_another_email'
      %form#mailee_form{ :action => '/mailee', :method => 'post' }
        = token_tag
        %fieldset
          %label{ :for => 'name' } Nome
          %br
          %input#name.title{ :name => 'name', :type => 'text', :tabindex => 6}
          %br
          %label{:for => 'email' } Email
          %br
          %input#email.title{ :name => 'email', :type => 'text', :tabindex => 7}
          %br
          %button#subscribe_newsletter_button{ :type => 'submit', :tabindex => 8}
            %span Cadastrar
          %p.quiet &asymp; 1 email por mês
          .clear
      :javascript
        $('#mailee_form').submit(function(){
          re = /^[a-z0-9\._-]+@([a-z0-9][a-z0-9-_]*[a-z0-9-_]\.)+([a-z-_]+\.)?([a-z-_]+)$/
          if(!this.email.value.match(re)) {
            alert("Confira o preenchimento do seu email.")
            this.email.focus()
            return false
          }
          var data = $(this).serialize()
          var url = $(this).attr('action')
          $.post(url, data, function(result){
            $('#mailee_form').fadeOut()
            if(result.ok){
              $('#mailee_ok').fadeIn()
            }else{
              $('#mailee_error').fadeIn()
            }
          }, 'json')
          return false
        })
        $('.subscribe_another_email').click(function(){
          $('#mailee_ok').hide()
          $('#mailee_form').fadeIn()
          return false
        })
  .clear
.colophon_wrapper{:style => 'overflow:visible;'}
  #colophon
    //#{link_to '', 'http://softa.com.br/', :id => 'softa_logo', :title => 'Softa'}
    %p.copyright_info 
      Copyright &copy; 
      = Time.now.year
    .clear
:javascript
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/qvPKQCbU5w4SxmYiM2od1w.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();

app/views/layouts/_google_analytics.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17717880-5']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_header.haml
.header_wrapper
  #login_signup_box
    #{link_to 'Login', '#', :id => :login_button, :title => 'Login'}
    #{link_to t('header.try_for_free'), signup_path, :id => :signup_button, :title => t('header.try_for_free')}
    .clear
  #logo= link_to image_tag('mailee_logo.png', :alt => 'Mailee.me', :title => 'Mailee.me · Email Marketing 2.0'), root_path
  %ul#navigation
    %li= link_to 'Home', root_path, :class => "#{selected(:index)} home"
    %li= link_to t('header.nav.tour'), tour_path, :class => "#{selected(:tour)} resources"
    %li= link_to t('header.nav.prices'), prices_path, :class => "#{selected(:prices)} prices"
    %li= link_to t('header.nav.signup'), signup_path, :class => "#{selected(:signup)} signup"
    %li= link_to 'Help', help_path, :class => "#{selected(:help)} help"
    %li= mail_to 'suporte@mailee.me', 'Contato'
  .clear
.clear
.page_overlay.login_form.hide
  #login_form_box
    .close_login_panel{:style => 'margin: -202px 0 0 252px;'}
      #{image_tag('close.png')}
    %iframe{ :src => global_login, :width => "500px", :height => "350px", :scrolling => "no", :frameborder => 0, :style => 'background-color: transparent;', :allowtransparency => "true" }

:javascript 
  logins = 0
  $('#login_button').click(function(){
    $('#flash_video').css({'visibility':'hidden'})
    $('.page_overlay.login_form').fadeIn('slow')
    //if( logins )
    //  $('#login_form_box iframe').attr('src',$('#login_form_box iframe').attr('src'))

    logins++
    return false
  })
  $('.close_login_panel').click(function(){
    $('.page_overlay').fadeOut('fast', function(){
      $('#flash_video').css({'visibility':'visible'})
    })
    return false
  })
  $('.page_overlay').click(function(){
    $('.page_overlay').fadeOut('fast', function(){    
      $('#flash_video').css({'visibility':'visible'}) 
    })
    
    return false
  })
  
:javascript
  var _kmq = _kmq || [];
  function _kms(u){
    setTimeout(function(){
      var s = document.createElement('script'); var f = document.getElementsByTagName('script')[0]; s.type = 'text/javascript'; s.async = true;
      s.src = u; f.parentNode.insertBefore(s, f);
    }, 1);
  }
  _kms('//i.kissmetrics.com/i.js');_kms('//doug1izaerwt3.cloudfront.net/92c26dc14e9f773aabbfec1caeb7ff3f6fed64fb.1.js');  

app/views/layouts/_signup_bar.haml
#easy_signup
  .easy_signup_wrapper
    %h1
      #{link_to t('easy_signup.see_the_prices'), prices_path, :class => 'prices' } ou #{link_to t('easy_signup.test_for_free'), signup_path, :class => 'signup'}.

app/views/layouts/site.html.haml
!!!5
%html{ :lang => t('lang')}
  %head
    %meta{ :charset => 'UTF-8' }
    /[if IE]
      %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge;chrome=1' }
    %meta{ :name => 'robots', :content => 'index, follow' }
    %title= @title
    = stylesheet_link_tag 'screen'
    %link{ :rel   => 'home',          :href      => 'http://mailee.me/' }
    %link{ :rel   => 'alternate',     :href      => 'http://blog.mailee.me/rss.xml', :type => 'application/rss+xml', :title => 'RSS' }
    %link{ :rel   => 'index',         :href      => 'http://mailee.me/sitemap' }
    %meta{ :name  => 'Author',        :content   => 'Panop.it' }
    %link{ :rel   => 'canonical',     :href      => 'http://mailee.me/' }
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Droid+Sans:bold'
    = javascript_include_tag 'jquery-1.4.2.min', 'jquery.cookie', 'referrer', 'jquery.animate-colors-min.js', 'http://html5shim.googlecode.com/svn/trunk/html5.js'
    /[if IE]
      = stylesheet_link_tag 'ie'
      = javascript_include_tag 'selectivizr/selectivizr'
      = javascript_include_tag 'ie6/jquery.reject.min'
      :javascript
        $(document).ready(function(){
          $.reject({
            display:     ['chrome', 'firefox','safari','msie','gcf'],
            header:       #{t('reject.header')},
            paragraph1:   #{t('reject.paragraph_one')},
            paragraph2:   #{t('reject.paragraph_two')},
            closeMessage: #{t('reject.close_message')},
            closeLink:    #{t('reject.close_link')},
            imagePath:    '../../images/browsers/',
            closeCookie:  true
          });
          return false;
        });
    = yield :metatags
    %link{ :rel => 'shortcut icon', :href => 'favicon.ico', :type => 'image/vnd.microsoft.icon' }
  %body{:id => selected_menu}
    #root
      %header= render('layouts/header')
      #content= yield
      = yield :signup_bar
      %footer= render('layouts/footer')
    = render('layouts/google_analytics')

app/views/site/_kase.html.haml
.key_feature{:style => 'width:469px;height: 400px; max-height: 400px', :class => cycle('first_box','last_box')}
  .key_feature_wrapper{:style => 'position:relative'}
    = image_tag "cases/#{img}.png", :class => 'case_img'
    %div{:style => 'height:100px'}
    %h2{:style => 'margin:0 !important;padding:0'}= name
    %p= raw bio
    %p= raw about
    %hr
    %p= raw desc
    .clear
  .clear

app/views/site/agencies/_head.html.haml
%meta{:charset => "UTF-8"}
-# <meta name="viewport" content="initial-scale=1.0, width=device-width, height=device-height, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
%title Mailee
= stylesheet_link_tag "/agencies/css/bootstrap.css"
= stylesheet_link_tag "/agencies/css/style.css"
= stylesheet_link_tag "/agencies/css/signup.css"

%link{:href => "http://fonts.googleapis.com/css?family=Droid+Sans:400,700", :media => "screen", :rel => "stylesheet", :type => "text/css"}
/ = stylesheet_link_tag "/agencies/css/signup.css"
%script{:charset => "utf-8", :src => "/agencies/javascripts/jquery.js", :type => "text/javascript"}
%script{:charset => "utf-8", :src => "/agencies/javascripts/scrollspy.js", :type => "text/javascript"}
= javascript_include_tag 'jquery.cookie', 'referrer'
-# Descomentar o carousel quando formos usar
  %script{:src => "/agencies/javascripts/jquery.carouFredSel.js", :type => "text/javascript"}

app/views/site/agencies/_header.html.haml
.social
  .center
    %ul.socials
      %li.facebook
        %a{:href => "http://www.facebook.com/Mailee.me", :target => "_blank"} Facebook
      %li.twitter
        %a{:href => "http://twitter.com/maileeme", :target => "_blank"} @maileeme
      %li.blog
        %a{:href => "http://blog.mailee.me/"} Blog
    %ul.actions
      %li
        %a#login_button.btn{:href => "#"} login
      %li
        %a.btn.scroll{:href => "#sign-up"} experimente
.menu
  .center
    %a#logo.scroll{:href => "#toptop"}
      %h1 Mailee
    %ul.nav
      %li.active
        %a.scroll{:href => "#recursos"}
          Recursos
          %span Conheça as funcionalidades
      %li
        %a.scroll{:href => "#prices"}
          Preços
          %span Agências têm preços diferenciados.
      %li
        %a.scroll{:href => "#sign-up"}
          Cadastre-se
          %span Receba 250 créditos para testes
      %li
        %a.scroll{:href => "#footer"}
          Contato
          %span Alguma dúvida? Fale com a gente!

.page_overlay.login_form.hide
  #login_form_box
    .close_login_panel{:style => 'margin: -202px 0 0 252px;'}
      #{image_tag('close.png')}
    %iframe{ :src => global_login, :width => "500px", :height => "350px", :scrolling => "no", :frameborder => 0, :style => 'background-color: transparent;', :allowtransparency => "true" }

:javascript 
  logins = 0
  $('#login_button').click(function(){
    $('#flash_video').css({'visibility':'hidden'})
    $('.page_overlay.login_form').fadeIn('slow')
    //if( logins )
    //  $('#login_form_box iframe').attr('src',$('#login_form_box iframe').attr('src'))

    logins++
    return false
  })
  $('.close_login_panel').click(function(){
    $('.page_overlay').fadeOut('fast', function(){
      $('#flash_video').css({'visibility':'visible'})
    })
    return false
  })
  $('.page_overlay').click(function(){
    $('.page_overlay').fadeOut('fast', function(){    
      $('#flash_video').css({'visibility':'visible'}) 
    })
    
    return false
  })

app/views/site/agencies/_prices.html.haml
#prices.center
  %h2 Preços
  %p
    Você compra um pacote de envios e pode usar ao longo do tempo que quiser.
    %br
    É como um celular pré-pago, só que seus créditos nunca expiram!
    %br
    Um crédito é igual a um envio para um contato.
  %ul
    %li
      %h5
        100 mil
        .credits créditos
      / %span 100 mil créditos
      %span.price 
        %em.rs R$ 224
        %sup.cents ,00
      %span IP dedicado: R$ 79,00/mês
      %span.desc R$ 202,00/mês<sup>*</sup>
      
      %a.btn.scroll{:href => "#sign-up"} cadastre-se
    %li
      %h5
        250 mil
        .credits créditos
      / %span 100 mil créditos
      %span.price 
        %em.rs R$ 432
        %sup.cents ,00
      %span IP dedicado: R$ 79,00/mês
      %span.desc R$ 390,00/mês<sup>*</sup>
      
      %a.btn.scroll{:href => "#sign-up"} cadastre-se
    %li.last
      %h5
        1 milhão
        .credits de créditos
      / %span 100 mil créditos
      %span.price 
        %em.rs R$ 1120
        %sup.cents ,00
      %span IP dedicado: R$ 79,00/mês
      %span.desc R$ 1010,00/mês<sup>*</sup> + IP dedicado 
      
      %a.btn.scroll{:href => "#sign-up"} cadastre-se
    %li.highlight
      %h5
        500 mil
        .credits créditos
      / %span 100 mil créditos
      %span.price
        %em.rs R$ 720
        %sup.cents ,00
      %span IP dedicado: R$ 79,00/mês
      %span.desc R$ 648,00/mês<sup>*</sup> + IP dedicado
      
      / %span.desc IP dedicado gratuito no pacote de 6 meses
      %a.btn.btn-success.scroll{:href => "#sign-up"} cadastre-se
.clear
%div.center{:style => 'padding-top: 1.5em; margin-bottom: 1.5em;'}
  %p
    %sup *
    Compra recorrente de no mínimo 6 meses.

app/views/site/apps/_showcase.html.haml
%style #showcase a{ color:#cdf }
#showcase
  .light
    .showcase_wrapper
      .showcase
        .description.span-12.last
          %h1.slideme Email as a Service
          %p.slideme
            O jeito certo de enviar
            emails da sua aplicação.
          %p.slideme
            Utilize o Mailee.me para enviar
            %br
            suas mensagens e saiba quem, quando
            %br
            e como suas mensagens estão sendo vistas.
          %h2.slideme
            %a.signup_now{ :href => signup_path } Experimente grátis &raquo;
        .slideme.span-12
          = image_tag 'mailee_eaas.png'
      .showcase{:style => 'display:none'}
        .span-11
          .showcase_image
            %div{:style => 'position:relative;'}
              = image_tag 'showcase/why_use.gif', :class => 'slideme'
              %div{:style => 'position:absolute; bottom:0; left:0; margin:-15px;'}
                - %w(one two three).each do |i|
                  = image_tag "showcase/why_use_block_#{i}.gif", :class => 'slideme image_shadow', :style => i == 'three' ? '' : 'margin-right:52px;'
        .span-12.prepend-1.last
          %ol{:style => 'font-size:2em'}
            %li.slideme Você cria uma conta no Mailee
            %li.slideme Sua aplicação utiliza a API para enviar emails
            %li.slideme Você sabe exatamente quem acessou as mensagens...
            %li.slideme ... e nunca mais se preocupa com a entrega.
      .showcase{:style => 'display:none'}
        .span-11.append-1
          %ul{:style => 'font-size:1.6em'}
            %li.slideme Você não se preocupa mais com entregabilidade
            %li.slideme Você sabe como, onde, quando e quem acessou seus emails
            %li.slideme Você pode enviar emails para datas futuras
            %li.slideme Você pode enviar emails para milhares de contatos, com uma ação só
            %li.slideme Seus templates são respeitados e você pode mudá-los de forma fácil
        .span-12.last
          .showcase_image
            %div{:style => 'position:relative;'}
              = image_tag 'showcase/designers.gif', :class => 'slideme'
              %div{:style => 'position:absolute; bottom:0; left:0; margin:-15px;'}
                - %w(one two three).each do |i|
                  = image_tag "showcase/design_block_#{i}.gif", :class => 'slideme image_shadow', :style => i == 'three' ? '' : 'margin-right:52px;'
      .showcase{ :style => 'display:none'}
        .span-12.last
          .showcase_image.slideme
            %div{:style => 'position:relative;'}
              = image_tag 'showcase/developers.gif', :class => 'slideme'
              %div{:style => 'position:absolute; bottom:0; left:0; margin:-15px;'}
                - %w(one two three).each do |i|
                  = image_tag "showcase/developers_block_#{i}.gif", :class => 'slideme image_shadow', :style => i == 'three' ? '' : 'margin-right:52px;'
        .span-11.prepend-1
          %ul{:style => 'font-size:2em'}
            %li.slideme #{link_to 'GEM', 'https://github.com/panopit/mailee-api'} para integração com Ruby on Rails
            %li.slideme Código para integração com #{link_to 'PHP', 'https://github.com/panopit/mailee-api-php'}
            %li.slideme Integração com loja virtual #{link_to 'SPREE', 'https://github.com/panopit/mailee_spree'} (Locaweb)
            %li.slideme Integração com CMS Drupal (em breve)
.showcase_selector
  .container
    %a.tab.on{ :href => "#" } EaaS
    %a.tab{ :href => "#" } como funciona?
    %a.tab{ :href => "#" } vantagens
    %a.tab{ :href => "#" } ferramentas

app/views/site/bad_browsers.haml
- content_for :metatags do
  %meta{ :name => 'Keywords', :content => 'Mailee.me, Mailee, Email, Marketing, 2.0' }
  %meta{ :name => 'Description', :content => 'Mailee.me · Crie templates, envie mensagens e acompanhe resultados em um só lugar. Email marketing 2.0 tem criador de templates, geolocalização, integração com redes sociais, e muito mais!' }
.content_wrapper
  .bad_browser
    .bad_browser_wrapper
      %h1 Navegador inválido
      %p
        %strong O seu navegador não é suportado pelo Mailee.me.
      %br
      %h2 O que fazer?
      %p Você pode fazer o download de um dos seguintes navegadores:
      %br
      %table#valid_browsers{ :cellpacing => 0, :cellpadding => 0}
        %tbody
          %tr
            %td
              %a{ :href => 'http://www.mozilla.com/pt-BR/'}
                = image_tag 'browsers/browser_firefox.gif'
                %br
                %strong Firefox 3+
            %td
              %a{ :href => 'http://www.google.com/chrome'}
                = image_tag 'browsers/browser_chrome.gif'
                %br
                %strong Chrome 5+
            %td
              %a{ :href => 'http://www.apple.com/safari/download'}
                = image_tag 'browsers/browser_safari.gif'
                %br
                %strong Safari 4+
            %td
              %a{ :href => 'http://www.opera.com/browser/download' }
                = image_tag 'browsers/browser_opera.gif'
                %br
                %strong Opera 9+
            %td
              %a{ :href => 'http://www.microsoft.com/brasil/windows/Internet-explorer/default.aspx'}
                = image_tag 'browsers/browser_msie.gif'
                %br
                %strong IE 8+

app/views/site/cases.html.haml
%style
  :sass
    .first_box .case_img
      position: absolute
      top: -10px
      left: 0px
    .last_box .case_img
      position: absolute
      top: -10px
      right: 0px

- content_for :metatags do
  %meta{ :name => 'Keywords', :content => 'Mailee.me, Mailee, Email, Marketing, 2.0' }
  %meta{ :name => 'Description', :content => 'Mailee.me · Crie templates, envie mensagens e acompanhe resultados em um só lugar. Email marketing 2.0 tem criador de templates, geolocalização, integração com redes sociais, e muito mais!' }
.content_wrapper
  #mailee_resources
    %h2 Cases
    = kase 'qbazar', 'Ike Moraes', "<strong>CEO</strong>, #{link_to 'Q!Bazar', 'http://www.qbazar.com.br', :target => :_blank}", "SÃO PAULO/SP &dash; O Q!Bazar é um evento tradicional de moda em São Paulo, criado em 2001.", "Estamos muito felizes com estes resultados [do Mailee] e esperamos que vocês se inspirem para encontrar soluções criativas para atingir seus objetivos utilizando o Mailee.me!<br /><strong>#{link_to 'Saiba mais »', 'http://blog.mailee.me/qbazarnet-um-caso-de-sucesso-de-e-commerce-us', :target => :_blank}</strong>"
    = kase 'mmda', 'Diego Martinez', "<strong>Sócio Diretor</strong>, #{link_to 'MMDA Digital', 'http://www.mmdadigital.com.br', :target => :_blank}", "PORTO ALEGRE/RS &dash; Desenvolvimento de sites e aplicações Web.", "O Mailee.me é um aplicativo de grande futuro, se destaca pela interface, desempenho e facilidade de uso. Também vale lembrar a agilidade da equipe de desenvolvimento no auxilio aos parceiros/clientes."
    = kase 'mega', 'Marcos Vinicius Bohrer', "<strong>Proprietário</strong>, #{link_to 'Mega Internet', 'http://www.megainternet.com.br', :target => :_blank}", 'CANELA E GRAMADO/RS &dash; Desenvolvimento de web-sites institucionais, lojas virtuais e hospedagem de sites', 'Após analisar diversas soluções no mercado, tanto nacional como internacional, e após a avaliação do serviço, optamos pelo Mailee.me por ser simples e intuitivo, e atendeu todas as nossas necessidades e dos nossos clientes.'
    = kase 'computech', 'Luciano Franz', "<strong>Diretor Técnico e Comercial</strong>, #{link_to 'Computech Tecnologia Ltda', 'http://www.wavelan.com.br', :target => :_blank}", 'PORTO ALEGRE/RS - Fabrica equipamentos para internet via rádio.', 'Usabilidade e entregabilidade excelentes. Qualquer um pode fazer marketing virtual com ele. Parabéns!!!'
    .clear
    %h2.contact_us
      %a{ :href => @commercial_mail } Quer compartilhar o seu case?

app/views/site/form_ok.haml
- content_for :metatags do
  %meta{ :name => 'Keywords', :content => 'Mailee.me, Mailee, Email, Marketing, 2.0' }
  %meta{ :name => 'Description', :content => 'Mailee.me · Crie templates, envie mensagens e acompanhe resultados em um só lugar. Email marketing 2.0 tem criador de templates, geolocalização, integração com redes sociais, e muito mais!' }
.content_wrapper
  %br
  .success
    %h6 Cadastro efetuado com sucesso.
  %a{:href => root_path } Voltar ao início

app/views/site/index.haml
%style #content{ padding:0 !important }
- content_for :metatags do
  %meta{ :name => 'Keywords', :content => 'Mailee.me, Mailee, Email, Marketing, 2.0' }
  %meta{ :name => 'Description', :content => 'Mailee.me · Crie templates, envie mensagens e acompanhe resultados em um só lugar. Email marketing 2.0 tem criador de templates, geolocalização, integração com redes sociais, e muito mais!' }
- content_for :signup_bar do
  = render('layouts/signup_bar')
= render('site/index/showcase')

.content_wrapper
  = render('site/index/social')
= javascript_include_tag 'index.js', :cache => true